### GET TASKS
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpZ2lvc2lsdmExIiwiaWF0IjoxNjMzNzI3MzM1LCJleHAiOjE2MzM3MzA5MzV9.M5D781CTDBgfmsSjhVrqatmN57AN6Qmnla5LYoR4GCY


### GET TASKS
GET http://localhost:3000/tasks?status=DONE&search=TASK
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpZ2lvc2lsdmEiLCJpYXQiOjE2MzM3MjcyOTksImV4cCI6MTYzMzczMDg5OX0.XxmcnZD6SbavzPN0jxyy_OYq7QY78jx6ohi02aTyLOE


### GET TASK BY ID
GET http://localhost:3000/tasks/b15395ca-7546-4165-a955-d5a8884dfa5c

### DELETE TASK
DELETE http://localhost:3000/tasks/0589fa7e-f69e-4778-a649-a11dfbcd0ed4

### ADD TASK
POST http://localhost:3000/tasks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpZ2lvc2lsdmEiLCJpYXQiOjE2MzM3MjcyOTksImV4cCI6MTYzMzczMDg5OX0.XxmcnZD6SbavzPN0jxyy_OYq7QY78jx6ohi02aTyLOE

{
  "title": "Minha task 5",
  "description": "Essa é minha taskinha"
}

### UPDATE TASK
PATCH http://localhost:3000/tasks/577ccbc5-2d43-40bd-a9c5-857a22dc3b3b/status
content-type: application/json

{
  "status": "DONE"
}